In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv

In [6]:
data=pd.read_csv(r"/kaggle/input/datasets/fredericobreno/play-tennis/play_tennis.csv")
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [7]:
data.shape

(14, 6)

In [8]:
data.isna().sum()

day         0
outlook     0
temp        0
humidity    0
wind        0
play        0
dtype: int64

In [9]:
data.duplicated().sum()

np.int64(0)

In [ ]:
# Problem 1

# outlook=high,temp=hot,humidity=high,wind=week
# play or not ?

In [11]:
# solution

# P(play / outlook=high,temp=hot,humidity=high,wind=week) = P(outlook=high / play) * P(temp=hot / play) * P(humidity=high / play) * P(wind=week / play) * P(play)
# P(not play / outlook=high,temp=hot,humidity=high,wind=week)=P(outlook=high / not play) * P(temp=hot / not play) * P(humidity=high / not play) * P(wind=week / not play) * P(play)

In [12]:
data

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [14]:
P_yes= 9/14
P_no= 5/14

In [15]:
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [30]:
P_outlook_overcast_yes=4/9
P_outlook_rain_yes=3/9
P_outlook_sunny_yes=2/9

P_outlook_overcast_no=0/5
P_outlook_rain_no=2/5
P_outlook_sunny_no=3/5

In [31]:
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [32]:
P_temp_cool_yes=3/9
P_temp_hot_yes=2/9
P_temp_mild_yes=4/9

P_temp_cool_no=1/5
P_temp_hot_no=2/5
P_temp_mild_no=2/5

In [33]:
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [34]:
P_humidity_high_yes=3/9
P_humidity_normal_yes=6/9

P_humidity_high_no=4/5
P_humidity_normal_no=1/5

In [35]:
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [40]:
P_wind_strong_yes=3/9
P_wind_weak_yes=6/9

P_wind_strong_no=3/5
P_wind_weak_no=2/5

In [41]:
# P(play / outlook=sunny,temp=hot,humidity=high,wind=weak) = P(outlook=sunny / play) * P(temp=hot / play) * P(humidity=high / play) * P(wind=week / play) * P(play)
# P(not play / outlook=sunny,temp=hot,humidity=high,wind=weak)=P(outlook=sunny / not play) * P(temp=hot / not play) * P(humidity=high / not play) * P(wind=week / not play) * P(play)

In [42]:
P_play_yes = P_outlook_sunny_yes * P_temp_hot_yes * P_humidity_high_yes * P_wind_weak_yes * P_yes
P_play_no = P_outlook_sunny_no * P_temp_hot_no * P_humidity_high_no * P_wind_weak_no * P_no

In [46]:
P_play_yes,P_play_no

(0.007054673721340387, 0.02742857142857143)