In [2]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv(r'customer.csv')
data.sample(5)

    age  gender   review education purchased
5    31  Female  Average    School       Yes
48   39  Female     Good        UG       Yes
24   16  Female  Average        PG       Yes
32   92    Male  Average        UG       Yes
30   73    Male  Average        UG        No

In [5]:
data = data.iloc[:,2:].copy()

In [6]:
data.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [11]:
data.shape

(50, 3)

In [9]:
data['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [10]:
data['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(data.drop(columns=['purchased']),data['purchased'],test_size=0.2,random_state=42)

In [14]:
X_train.shape,X_test.shape

((40, 2), (10, 2))

In [20]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
X_train_oe=oe.fit_transform(X_train)
X_test_oe=oe.transform(X_test)
X_test_oe

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [21]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [26]:
le=LabelEncoder()

y_train=le.fit_transform(y_train)
y_test=le.transform(y_test)

In [27]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [28]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [29]:
# One Hot Encoding

In [30]:
data=pd.read_csv(r"cars.csv")
data.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [31]:
data['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [32]:
# implementation using pandas

In [34]:
pd.get_dummies(data,columns=['fuel','owner'],dtype='int')

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

In [37]:
pd.get_dummies(data,columns=['fuel','owner'],drop_first=True,dtype='int')

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [41]:
X_train,X_test,y_train,y_test = train_test_split(data.iloc[:,0:4],data.iloc[:,-1],test_size=0.2,random_state=2)
X_train.shape,X_test.shape

((6502, 4), (1626, 4))

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [53]:
ohe = OneHotEncoder(drop='first',sparse_output=False)

In [55]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_train_new.shape

(6502, 7)

In [60]:
X_test_new = ohe.transform(X_test[['fuel','owner']])
X_test_new.shape

(1626, 7)

In [70]:
pd.DataFrame(np.concatenate([X_train[['brand','km_driven']],X_train_new],axis=1)).head()

          0       1    2    3    4    5    6    7    8
0   Hyundai   35000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
1      Jeep   60000  1.0  0.0  0.0  0.0  0.0  0.0  0.0
2   Hyundai   25000  0.0  0.0  1.0  0.0  0.0  0.0  0.0
3  Mahindra  130000  1.0  0.0  0.0  0.0  1.0  0.0  0.0
4   Hyundai  155000  1.0  0.0  0.0  0.0  0.0  0.0  0.0

In [64]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [74]:
counts = data['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [76]:
data['brand'].nunique()
threshold = 100

32

In [77]:
repl = counts[counts <= threshold].index

In [87]:
pd.get_dummies(data['brand'].replace(repl, 'uncommon'),dtype='int').head(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0

In [88]:
# frequency encoding,count encoding

In [89]:

df = pd.DataFrame({
    "City":["Delhi","Mumbai","Delhi","Chennai","Delhi","Mumbai"]
})

freq = df["City"].value_counts()

df["City_encoded"] = df["City"].map(freq)

print(df)

      City  City_encoded
0    Delhi             3
1   Mumbai             2
2    Delhi             3
3  Chennai             1
4    Delhi             3
5   Mumbai             2

In [91]:
import category_encoders as ce

In [92]:
# Binary Encoding

df = pd.DataFrame({
    "City": [
        "Delhi",
        "Mumbai",
        "Chennai",
        "Surat",
        "Rajkot"
    ]
})

encoder = ce.BinaryEncoder(cols=["City"])

encoded = encoder.fit_transform(df)

print(encoded)

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1

In [93]:
# Target Encoding

df = pd.DataFrame({
    "City":["Delhi","Delhi","Mumbai","Mumbai","Chennai"],
    "Purchased":[1,0,0,0,1]
})

mean = df.groupby("City")["Purchased"].mean()

df["City_Encoded"] = df["City"].map(mean)

print(df)

      City  Purchased  City_Encoded
0    Delhi          1           0.5
1    Delhi          0           0.5
2   Mumbai          0           0.0
3   Mumbai          0           0.0
4  Chennai          1           1.0