In [86]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler,RobustScaler,StandardScaler,OrdinalEncoder,MaxAbsScaler
from sklearn.metrics import accuracy_score

In [53]:
data=pd.read_csv(r"E:\Datasets\loan_approval_dataset.csv")
data.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [54]:
data.drop(columns=['loan_id'],inplace=True)

In [55]:
data.shape

(4269, 12)

In [56]:
data.isna().sum()

no_of_dependents            0
education                   0
self_employed               0
income_annum                0
loan_amount                 0
loan_term                   0
cibil_score                 0
residential_assets_value    0
commercial_assets_value     0
luxury_assets_value         0
bank_asset_value            0
loan_status                 0
dtype: int64

In [57]:
data.duplicated().sum()

np.int64(0)

In [58]:
data.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [59]:
data.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [60]:
data.columns=data.columns.str.strip()

In [61]:
data.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [62]:
data['self_employed'].value_counts()

self_employed
Yes    2150
No     2119
Name: count, dtype: int64

In [68]:
    def c_education(data):
        text=data.strip()
        if text=="Graduate":
            return 1
        else:
            return 0
    def c_employee(data):
        text=data.strip()
        if text=="Yes":
            return 1
        else:
            return 0

In [69]:
data['education']=data['education'].apply(c_education)
data['self_employed']=data['self_employed'].apply(c_employee)

In [70]:
data.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [71]:
data['loan_status']=data['loan_status'].str.strip().map({"Approved":1,'Rejected':0})

In [72]:
data.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,1,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,1
1,0,0,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,0
2,3,1,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,0
3,3,1,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,0
4,5,0,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,0

In [74]:
X_train,X_test,y_train,y_test=train_test_split(data.drop(columns=['loan_status']),data['loan_status'],test_size=0.33,random_state=42)

(2860, 11)

In [82]:
lr=LogisticRegression()
lr.fit(X_train,y_train)

y_pred1=lr.predict(X_test)
score1=accuracy_score(y_test,y_pred1)
score1

C:\Users\PRASHANT\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7295954577714692

In [88]:
scaler1=StandardScaler()
X_train1=scaler1.fit_transform(X_train)
X_test1=scaler1.transform(X_test)

scaler2=MinMaxScaler()
X_train2=scaler2.fit_transform(X_train)
X_test2=scaler2.transform(X_test)

scaler3=RobustScaler()
X_train3=scaler3.fit_transform(X_train)
X_test3=scaler3.transform(X_test)

scaler4=MaxAbsScaler()
X_train4=scaler4.fit_transform(X_train)
X_test4=scaler4.transform(X_test)

In [83]:
# standard scaler
lr1=LogisticRegression()
lr1.fit(X_train1,y_train)

y_pred1=lr1.predict(X_test1)
score1=accuracy_score(y_test,y_pred1)
score1

0.9048970901348474

In [84]:
# minmax scaler
lr2=LogisticRegression()
lr2.fit(X_train2,y_train)

y_pred2=lr2.predict(X_test2)
score2=accuracy_score(y_test,y_pred2)
score2

0.9127040454222853

In [85]:
# robust scaler
lr3=LogisticRegression()
lr3.fit(X_train3,y_train)

y_pred3=lr3.predict(X_test3)
score3=accuracy_score(y_test,y_pred3)
score3

0.9041873669268985

In [89]:
# Maxabs scaler
lr4=LogisticRegression()
lr4.fit(X_train4,y_train)

y_pred4=lr4.predict(X_test4)
score4=accuracy_score(y_test,y_pred4)
score4

0.9098651525904897