In [1]:
import pandas as pd
import numpy as np

In [2]:
imdb=pd.read_csv("imdb-top-1000.csv")
imdb.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [3]:
genre=imdb.groupby('Genre')

In [4]:
genre['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [5]:
genre['IMDB_Rating'].mean().sort_values(ascending=False).head(3)

Genre
Western    8.350000
Crime      8.016822
Fantasy    8.000000
Name: IMDB_Rating, dtype: float64

In [6]:
imdb.groupby(by='Director')['No_of_Votes'].sum().sort_values(ascending=False).head(3)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
Name: No_of_Votes, dtype: int64

In [7]:
genre[['IMDB_Rating','Series_Title']].max().head(2)

           IMDB_Rating Series_Title
Genre
Action             9.0      Yôjinbô
Adventure          8.6   Zombieland

In [8]:
# other option value_counts
imdb.groupby('Star1')['Genre'].count().sort_values(ascending=False).head(5)

Star1
Tom Hanks          12
Robert De Niro     11
Clint Eastwood     10
Al Pacino          10
Humphrey Bogart     9
Name: Genre, dtype: int64

In [9]:
genre.size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [10]:
genre.nth(6)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [11]:
genre.get_group('Mystery').shape

(12, 10)

In [12]:
imdb[imdb['Genre']=='Mystery'].shape

(12, 10)

In [13]:
genre.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

In [14]:
genre.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [15]:
genre.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
217,Ford v Ferrari,2019,152,Action,8.1,James Mangold,Matt Damon,291289,117624028.0,81.0
781,Harry Potter and the Goblet of Fire,2005,157,Adventure,7.7,Mike Newell,Daniel Radcliffe,548619,290013036.0,81.0
101,Toy Story,1995,81,Animation,8.3,John Lasseter,Tom Hanks,887429,191796233.0,95.0
766,The Last King of Scotland,2006,123,Biography,7.7,Kevin Macdonald,James McAvoy,175355,17605861.0,74.0
630,Adams æbler,2005,94,Comedy,7.8,Anders Thomas Jensen,Ulrich Thomsen,45717,1305.0,51.0
723,Wind River,2017,107,Crime,7.7,Taylor Sheridan,Kelsey Asbille,205444,33800859.0,73.0
422,Fiddler on the Roof,1971,181,Drama,8.0,Norman Jewison,Topol,39491,80500000.0,67.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
568,Nosferatu,1922,94,Fantasy,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
309,The Third Man,1949,104,Film-Noir,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
12,"Il buono, il brutto, il cattivo",1966,161,Western,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [16]:
genre.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [17]:
genre.agg({'Runtime':'mean','IMDB_Rating':"max"})

              Runtime  IMDB_Rating
Genre
Action     129.046512          9.0
Adventure  134.111111          8.6
Animation   99.585366          8.6
Biography  136.022727          8.9
Comedy     112.129032          8.6
Crime      126.392523          9.2
Drama      124.737024          9.3
Family     107.500000          7.8
Fantasy     85.000000          8.1
Film-Noir  104.000000          8.1
Horror     102.090909          8.5
Mystery    119.083333          8.4
Thriller   108.000000          7.8
Western    148.250000          8.8

In [18]:
genre.agg(['count','max'])

          Series_Title                                      Released_Year  \
                 count                                  max         count
Genre
Action             172                              Yôjinbô           172
Adventure           72                           Zombieland            72
Animation           82          Ôkami kodomo no Ame to Yuki            82
Biography           88                              Zerkalo            88
Comedy             155             Zindagi Na Milegi Dobara           155
Crime              107                    À bout de souffle           107
Drama              289                            Zwartboek           289
Family               2  Willy Wonka & the Chocolate Factory             2
Fantasy              2                            Nosferatu             2
Film-Noir            3                        The Third Man             3
Horror              11                            The Thing            11
Mystery             12                              Vertigo            12
Thriller             1                      Wait Until Dark             1
Western              4               The Outlaw Josey Wales             4

                Runtime      IMDB_Rating      Director                    \
            max   count  max       count  max    count               max
Genre
Action     2019     172  321         172  9.0      172       Zack Snyder
Adventure    PG      72  228          72  8.6       72  Ömer Faruk Sorak
Animation  2020      82  137          82  8.6       82   Yoshifumi Kondô
Biography  2020      88  209          88  8.9       88      Tom McCarthy
Comedy     2020     155  188         155  8.6      155       Zoya Akhtar
Crime      2019     107  229         107  9.2      107      Yavuz Turgul
Drama      2020     289  242         289  9.3      289       Çagan Irmak
Family     1982       2  115           2  7.8        2  Steven Spielberg
Fantasy    1922       2   94           2  8.1        2      Robert Wiene
Film-Noir  1949       3  108           3  8.1        3       John Huston
Horror     2017      11  122          11  8.5       11  William Friedkin
Mystery    2012      12  138          12  8.4       12     Terry Gilliam
Thriller   1967       1  108           1  7.8        1     Terence Young
Western    1976       4  165           4  8.8        4      Sergio Leone

          Star1                   No_of_Votes          Gross               \
          count               max       count      max count          max
Genre
Action      172      Yun-Fat Chow         172  2303232   172  936662225.0
Adventure    72      Yves Montand          72  1512360    72  874211619.0
Animation    82      Yôji Matsuda          82   999790    82  873839108.0
Biography    88     Éric Toledano          88  1213505    88  753585104.0
Comedy      155  Ömer Faruk Sorak         155   939631   155  886752933.0
Crime       107    Vincent Cassel         107  1826188   107  790482117.0
Drama       289    Çetin Tekindor         289  2343110   289  924558264.0
Family        2      Henry Thomas           2   372490     2  435110554.0
Fantasy       2     Werner Krauss           2    88794     2  445151978.0
Film-Noir     3     Teresa Wright           3   158731     3  123353292.0
Horror       11  Sigourney Weaver          11   787806    11  298791505.0
Mystery      12       Vidya Balan          12  1129894    12  474203697.0
Thriller      1    Audrey Hepburn           1    27733     1   17550741.0
Western       4       Henry Fonda           4   688390     4   31800000.0

          Metascore
              count    max
Genre
Action          143   98.0
Adventure        64  100.0
Animation        75   96.0
Biography        79   97.0
Comedy          125   99.0
Crime            87  100.0
Drama           241  100.0
Family            2   91.0
Fantasy           0    NaN
Film-Noir         3   97.0
Horror           11   97.0
Mystery           8  100.0
Thriller          1   81.0
Western           4   90.0

In [19]:
len(genre)

14

In [20]:
result = []

for group, data in genre:
    result.append(
        data[data['IMDB_Rating'] == data['IMDB_Rating'].max()]
    )

result = pd.concat(result)

In [21]:
result[['Series_Title','IMDB_Rating']].head(5)

                     Series_Title  IMDB_Rating
2                 The Dark Knight          9.0
21                   Interstellar          8.6
23  Sen to Chihiro no kamikakushi          8.6
7                Schindler's List          8.9
19                   Gisaengchung          8.6

In [22]:
result = imdb.loc[imdb.groupby('Genre')['IMDB_Rating'].idxmax()]

In [23]:
def rank_movies(group):
    group['Genre_Rank']=group['IMDB_Rating'].rank(ascending=False)
    return group
genre.apply(rank_movies)

C:\Users\PRASHANT\AppData\Local\Temp\ipykernel_8760\1048351806.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genre.apply(rank_movies)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              Genre_Rank
Genre
Action   2           1.0
         5           2.0
         8           3.5
         10          3.5
         13          6.0
...                  ...
Thriller 700         1.0
Western  12          1.0
         48          2.0
         115         3.0
         691         4.0

[1000 rows x 11 columns]

In [24]:
duo=imdb.groupby(['Director','Star1'])

In [27]:
for group,data in duo:
    print(group,len(data))

('Aamir Khan', 'Amole Gupte') 1
('Aaron Sorkin', 'Eddie Redmayne') 1
('Abdellatif Kechiche', 'Léa Seydoux') 1
('Abhishek Chaubey', 'Shahid Kapoor') 1
('Abhishek Kapoor', 'Amit Sadh') 1
('Adam Elliot', 'Toni Collette') 1
('Adam McKay', 'Christian Bale') 1
('Aditya Chopra', 'Shah Rukh Khan') 1
('Aditya Dhar', 'Vicky Kaushal') 1
('Akira Kurosawa', 'Takashi Shimura') 1
('Akira Kurosawa', 'Tatsuya Nakadai') 2
('Akira Kurosawa', 'Toshirô Mifune') 7
('Alain Resnais', 'Emmanuelle Riva') 1
('Alan J. Pakula', 'Dustin Hoffman') 1
('Alan Parker', 'Bob Geldof') 1
('Alan Parker', 'Brad Davis') 1
('Alan Parker', 'Gene Hackman') 1
('Alejandro Amenábar', 'Eduardo Noriega') 1
('Alejandro Amenábar', 'Javier Bardem') 1
('Alejandro Amenábar', 'Nicole Kidman') 1
('Alejandro G. Iñárritu', 'Emilio Echevarría') 1
('Alejandro G. Iñárritu', 'Leonardo DiCaprio') 1
('Alejandro G. Iñárritu', 'Michael Keaton') 1
('Alejandro G. Iñárritu', 'Sean Penn') 1
('Alejandro Jodorowsky', 'Alejandro Jodorowsky') 1
('Alex Garland', 'Alicia Vikander') 1
('Alex Proyas', 'Rufus Sewell') 1
('Alexander Mackendrick', 'Alec Guinness') 1
('Alexander Mackendrick', 'Burt Lancaster') 1
('Alexander Payne', 'Bruce Dern') 1
('Alfonso Cuarón', 'Daniel Radcliffe') 1
('Alfonso Cuarón', 'Julianne Moore') 1
('Alfonso Cuarón', 'Liesel Matthews') 1
('Alfonso Cuarón', 'Maribel Verdú') 1
('Alfonso Cuarón', 'Sandra Bullock') 1
('Alfonso Cuarón', 'Yalitza Aparicio') 1
('Alfonso Gomez-Rejon', 'Thomas Mann') 1
('Alfred Hitchcock', 'Anthony Perkins') 1
('Alfred Hitchcock', 'Cary Grant') 2
('Alfred Hitchcock', 'Farley Granger') 1
('Alfred Hitchcock', 'James Stewart') 3
('Alfred Hitchcock', 'Laurence Olivier') 1
('Alfred Hitchcock', 'Margaret Lockwood') 1
('Alfred Hitchcock', 'Ray Milland') 1
('Alfred Hitchcock', 'Robert Donat') 1
('Alfred Hitchcock', 'Rod Taylor') 1
('Alfred Hitchcock', 'Tallulah Bankhead') 1
('Alfred Hitchcock', 'Teresa Wright') 1
('Amit Ravindernath Sharma', 'Ayushmann Khurrana') 1
('Anders Thomas Jensen', 'Ulrich Thomsen') 1
('Andrei Tarkovsky', 'Alisa Freyndlikh') 1
('Andrei Tarkovsky', 'Anatoliy Solonitsyn') 1
('Andrei Tarkovsky', 'Eduard Abalov') 1
('Andrei Tarkovsky', 'Margarita Terekhova') 1
('Andrei Tarkovsky', 'Natalya Bondarchuk') 1
('Andrew Adamson', 'Vicky Jenson') 1
('Andrew Davis', 'Harrison Ford') 1
('Andrew Lau', 'Alan Mak') 1
('Andrew Niccol', 'Ethan Hawke') 1
('Andrew Niccol', 'Nicolas Cage') 1
('Andrew Stanton', 'Ben Burtt') 1
('Andrew Stanton', 'Lee Unkrich') 1
('Andrey Zvyagintsev', 'Aleksey Serebryakov') 1
('Andrey Zvyagintsev', 'Maryana Spivak') 1
('Andrey Zvyagintsev', 'Vladimir Garin') 1
('Aneesh Chaganty', 'John Cho') 1
('Ang Lee', 'Emma Thompson') 1
('Ang Lee', 'Jake Gyllenhaal') 1
('Ang Lee', 'Suraj Sharma') 1
('Ang Lee', 'Yun-Fat Chow') 1
('Aniruddha Roy Chowdhury', 'Taapsee Pannu') 1
('Anthony Harvey', "Peter O'Toole") 1
('Anthony Russo', 'Joe Russo') 4
('Antoine Fuqua', 'Denzel Washington') 1
('Anton Corbijn', 'Sam Riley') 1
('Anurag Basu', 'Ranbir Kapoor') 1
('Anurag Kashyap', 'Abhay Deol') 1
('Anurag Kashyap', 'Manoj Bajpayee') 1
('Arthur Penn', 'Warren Beatty') 1
('Asghar Farhadi', 'Bérénice Bejo') 1
('Asghar Farhadi', 'Golshifteh Farahani') 1
('Asghar Farhadi', 'Payman Maadi') 1
('Asghar Farhadi', 'Shahab Hosseini') 1
('Ashutosh Gowariker', 'Aamir Khan') 1
('Ashutosh Gowariker', 'Shah Rukh Khan') 1
('Barry Levinson', 'Dustin Hoffman') 1
('Barry Levinson', 'Robert De Niro') 1
('Ben Affleck', 'Ben Affleck') 1
('Ben Affleck', 'Morgan Freeman') 1
('Bennett Miller', 'Brad Pitt') 1
('Bernardo Bertolucci', 'Jean-Louis Trintignant') 1
('Bernardo Bertolucci', 'John Lone') 1
('Billy Bob Thornton', 'Billy Bob Thornton') 1
('Billy Wilder', 'Fred MacMurray') 1
('Billy Wilder', 'Humphrey Bogart') 1
('Billy Wilder', 'Jack Lemmon') 1
('Billy Wilder', 'Kirk Douglas') 1
('Billy Wilder', 'Marilyn Monroe') 1
('Billy Wilder', 'Ray Milland') 1
('Billy Wilder', 'Tyrone Power') 1
('Billy Wilder', 'William Holden') 2
('Blake Edwards', 'Audrey Hepburn') 1
('Boaz Yakin', 'Denzel Washington') 1
('Bob Clark', 'Peter Billingsley') 1
('Bob Fosse', 'Liza Minnelli') 1
('Bob Fosse', 'Roy Scheider') 1
('Bob Gale', 'James Marsden') 1
('Bob Persichetti', 'Peter Ramsey') 1
('Bong Joon Ho', 'Hye-ja Kim') 1
('Bong Joon Ho', 'Kang-ho Song') 2
('Brad Anderson', 'Christian Bale') 1
('Brad Bird', 'Craig T. Nelson') 2
('Brad Bird', 'Eli Marienthal') 1
('Brad Bird', 'Jan Pinkava') 1
('Bradley Cooper', 'Lady Gaga') 1
('Brian De Palma', 'Al Pacino') 2
('Brian De Palma', 'Kevin Costner') 1
('Brian G. Hutton', 'Clint Eastwood') 1
('Brian G. Hutton', 'Richard Burton') 1
('Brian Henson', 'Michael Caine') 1
('Bruce Robinson', 'Richard E. Grant') 1
('Bryan Singer', 'Kevin Spacey') 1
('Bryan Singer', 'Patrick Stewart') 1
('Bryan Singer', 'Rami Malek') 1
('Buster Keaton', 'Buster Keaton') 1
('Byron Howard', 'Rich Moore') 1
('Cameron Crowe', 'Billy Crudup') 1
('Can Ulkay', 'Erdem Can') 1
('Carl Theodor Dreyer', 'Maria Falconetti') 1
('Carol Reed', 'Orson Welles') 1
('Cary Joji Fukunaga', 'Abraham Attah') 1
('Cecil B. DeMille', 'Charlton Heston') 1
('Chan-wook Park', 'Choi Min-sik') 1
('Chan-wook Park', 'Kang-ho Song') 1
('Chan-wook Park', 'Kim Min-hee') 1
('Chan-wook Park', 'Lee Yeong-ae') 1
('Charles Chaplin', 'Charles Chaplin') 6
('Charles Laughton', 'Robert Mitchum') 1
('Charles Vidor', 'Rita Hayworth') 1
('Charlie Kaufman', 'Philip Seymour Hoffman') 1
('Chris Columbus', 'Daniel Radcliffe') 1
('Chris Columbus', 'Macaulay Culkin') 1
('Christian Carion', 'Diane Kruger') 1
('Christophe Barratier', 'Gérard Jugnot') 1
('Christopher McQuarrie', 'Tom Cruise') 1
('Christopher Miller', 'Phil Lord') 1
('Christopher Nolan', 'Christian Bale') 4
('Christopher Nolan', 'Fionn Whitehead') 1
('Christopher Nolan', 'Guy Pearce') 1
('Christopher Nolan', 'Leonardo DiCaprio') 1
('Christopher Nolan', 'Matthew McConaughey') 1
('Clint Eastwood', 'Angelina Jolie') 1
('Clint Eastwood', 'Clint Eastwood') 4
('Clint Eastwood', 'Hilary Swank') 1
('Clint Eastwood', 'Ken Watanabe') 1
('Clint Eastwood', 'Sean Penn') 1
('Clyde Bruckman', 'Buster Keaton') 1
('Cristian Mungiu', 'Anamaria Marinca') 1
('Curtis Hanson', 'Kevin Spacey') 1
('Cy Endfield', 'Stanley Baker') 1
('Céline Sciamma', 'Noémie Merlant') 1
('Damien Chazelle', 'Miles Teller') 1
('Damien Chazelle', 'Ryan Gosling') 1
('Damián Szifron', 'Darío Grandinetti') 1
('Dan Gilroy', 'Jake Gyllenhaal') 1
('Daniel Monzón', 'Luis Tosar') 1
('Danis Tanovic', 'Branko Djuric') 1
('Danny Boyle', 'Cillian Murphy') 1
('Danny Boyle', 'Ewan McGregor') 1
('Danny Boyle', 'Loveleen Tandan') 1
('Darius Marder', 'Riz Ahmed') 1
('Darren Aronofsky', 'Ellen Burstyn') 1
('Darren Aronofsky', 'Mickey Rourke') 1
('Darren Aronofsky', 'Natalie Portman') 1
('David Ayer', 'Jake Gyllenhaal') 1
('David Cronenberg', 'Naomi Watts') 1
('David Fincher', 'Ben Affleck') 1
('David Fincher', 'Brad Pitt') 2
('David Fincher', 'Daniel Craig') 1
('David Fincher', 'Jake Gyllenhaal') 1
('David Fincher', 'Jesse Eisenberg') 1
('David Fincher', 'Michael Douglas') 1
('David Fincher', 'Morgan Freeman') 1
('David Lean', 'Celia Johnson') 1
('David Lean', 'Omar Sharif') 1
('David Lean', "Peter O'Toole") 1
('David Lean', 'William Holden') 1
('David Leitch', 'Ryan Reynolds') 1
('David Lynch', 'Anthony Hopkins') 1
('David Lynch', 'Bill Pullman') 1
('David Lynch', 'Isabella Rossellini') 1
('David Lynch', 'Naomi Watts') 1
('David Lynch', 'Richard Farnsworth') 1
('David Mackenzie', 'Chris Pine') 1
('David Mickey Evans', 'Tom Guiry') 1
('David O. Russell', 'Bradley Cooper') 1
('David O. Russell', 'Mark Wahlberg') 1
('David Yates', 'Daniel Radcliffe') 3
('David Zucker', 'Leslie Nielsen') 1
('Dean DeBlois', 'Chris Sanders') 1
('Dean DeBlois', 'Jay Baruchel') 1
('Denis Villeneuve', 'Amy Adams') 1
('Denis Villeneuve', 'Emily Blunt') 1
('Denis Villeneuve', 'Harrison Ford') 1
('Denis Villeneuve', 'Hugh Jackman') 1
('Denis Villeneuve', 'Lubna Azabal') 1
('Deniz Gamze Ergüven', 'Günes Sensoy') 1
('Dennis Gansel', 'Jürgen Vogel') 1
('Destin Daniel Cretton', 'Brie Larson') 1
('Destin Daniel Cretton', 'Michael B. Jordan') 1
('Don Hall', 'Chris Williams') 1
('Don Siegel', 'Clint Eastwood') 2
('Don Siegel', 'Kevin McCarthy') 1
('Dorota Kobiela', 'Hugh Welchman') 1
('Doug Liman', 'Franka Potente') 1
('Doug Liman', 'Tom Cruise') 1
('Duncan Jones', 'Sam Rockwell') 1
('Edgar Wright', 'Ansel Elgort') 1
('Edgar Wright', 'Simon Pegg') 2
('Edward Zwick', 'Leonardo DiCaprio') 1
('Edward Zwick', 'Matthew Broderick') 1
('Edward Zwick', 'Tom Cruise') 1
('Elem Klimov', 'Aleksey Kravchenko') 1
('Elia Kazan', 'James Dean') 1
('Elia Kazan', 'Marlon Brando') 1
('Elia Kazan', 'Vivien Leigh') 1
('Emir Kusturica', 'Bajram Severdzan') 1
('Emir Kusturica', 'Davor Dujmovic') 1
('Emir Kusturica', "Predrag 'Miki' Manojlovic") 1
('Eric Bress', 'J. Mackye Gruber') 1
('Ericson Core', 'Willem Dafoe') 1
('Ernst Lubitsch', 'Carole Lombard') 1
('Ernst Lubitsch', 'Margaret Sullavan') 1
('Ethan Coen', 'Joel Coen') 2
('F. Gary Gray', "O'Shea Jackson Jr.") 1
('F.W. Murnau', "George O'Brien") 1
('F.W. Murnau', 'Max Schreck') 1
('Fabián Bielinsky', 'Ricardo Darín') 1
('Farhan Akhtar', 'Aamir Khan') 1
('Fatih Akin', 'Baki Davrak') 1
('Fatih Akin', 'Birol Ünel') 1
('Federico Fellini', 'Anthony Quinn') 1
('Federico Fellini', 'Giulietta Masina') 1
('Federico Fellini', 'Magali Noël') 1
('Federico Fellini', 'Marcello Mastroianni') 2
('Felix van Groeningen', 'Veerle Baetens') 1
('Fernando Meirelles', 'Kátia Lund') 1
('Florian Henckel von Donnersmarck', 'Ulrich Mühe') 1
('Francis Ford Coppola', 'Al Pacino') 2
('Francis Ford Coppola', 'Gene Hackman') 1
('Francis Ford Coppola', 'Marlon Brando') 1
('Francis Ford Coppola', 'Martin Sheen') 1
('Francis Lee', "Josh O'Connor") 1
('Francis Veber', 'Thierry Lhermitte') 1
('Frank Capra', 'Cary Grant') 1
('Frank Capra', 'Clark Gable') 1
('Frank Capra', 'James Stewart') 2
('Frank Darabont', 'Tim Robbins') 1
('Frank Darabont', 'Tom Hanks') 1
('Frank Miller', 'Quentin Tarantino') 1
('Franklin J. Schaffner', 'Charlton Heston') 1
('Franklin J. Schaffner', 'George C. Scott') 1
('Franklin J. Schaffner', 'Steve McQueen') 1
('François Truffaut', 'Jean-Pierre Léaud') 1
('François Truffaut', 'Jeanne Moreau') 1
('Fred Zinnemann', 'Burt Lancaster') 1
('Fred Zinnemann', 'Edward Fox') 1
('Fred Zinnemann', 'Gary Cooper') 1
('Fred Zinnemann', 'Paul Scofield') 1
('Fritz Lang', 'Brigitte Helm') 1
('Fritz Lang', 'Peter Lorre') 1
('Gabriele Muccino', 'Will Smith') 2
('Gareth Edwards', 'Felicity Jones') 1
('Gareth Evans', 'Iko Uwais') 2
('Garth Davis', 'Dev Patel') 1
('Gary Trousdale', 'Kirk Wise') 1
('Gauri Shinde', 'Sridevi') 1
("Gavin O'Connor", 'Tom Hardy') 1
('Gayatri', 'Pushkar') 1
('Gene Saks', 'Jack Lemmon') 1
('George A. Romero', 'David Emge') 1
('George A. Romero', 'Duane Jones') 1
('George Cukor', 'Audrey Hepburn') 1
('George Cukor', 'Cary Grant') 1
('George Lucas', 'Mark Hamill') 1
('George Miller', 'Mel Gibson') 1
('George Miller', 'Tom Hardy') 1
('George P. Cosmatos', 'Kevin Jarre') 1
('George Roy Hill', 'Paul Newman') 2
('George Seaton', 'Edmund Gwenn') 1
('George Sluizer', 'Bernard-Pierre Donnadieu') 1
('George Stevens', 'Elizabeth Taylor') 1
('Georges Franju', 'Pierre Brasseur') 1
('Gillo Pontecorvo', 'Brahim Hadjadj') 1
('Giuseppe Tornatore', 'Geoffrey Rush') 1
('Giuseppe Tornatore', 'Philippe Noiret') 1
('Giuseppe Tornatore', 'Tim Roth') 1
('Gore Verbinski', 'Johnny Depp') 1
('Gregg Araki', 'Brady Corbet') 1
('Gregory Hoblit', 'Richard Gere') 1
('Greta Gerwig', 'Saoirse Ronan') 1
('Guillermo del Toro', 'Ivana Baquero') 1
('Gus Van Sant', 'Robin Williams') 1
('Guy Hamilton', 'Sean Connery') 1
('Guy Ritchie', 'Jason Flemyng') 1
('Guy Ritchie', 'Jason Statham') 1
('Guy Ritchie', 'Matthew McConaughey') 1
('Guy Ritchie', 'Robert Downey Jr.') 1
('Hal Ashby', 'Peter Sellers') 1
('Hal Ashby', 'Ruth Gordon') 1
('Hannes Holm', 'Rolf Lassgård') 1
('Harold Ramis', 'Bill Murray') 1
('Hayao Miyazaki', 'Cate Blanchett') 1
('Hayao Miyazaki', 'Chieko Baishô') 1
('Hayao Miyazaki', 'Daveigh Chase') 1
('Hayao Miyazaki', 'Hideaki Anno') 1
('Hayao Miyazaki', 'Hitoshi Takagi') 1
('Hayao Miyazaki', 'Kirsten Dunst') 1
('Hayao Miyazaki', 'Mayumi Tanaka') 1
('Hayao Miyazaki', 'Shûichirô Moriyama') 1
('Hayao Miyazaki', 'Sumi Shimamoto') 1
('Hayao Miyazaki', 'Yasuo Yamada') 1
('Hayao Miyazaki', 'Yôji Matsuda') 1
('Henri-Georges Clouzot', 'Simone Signoret') 1
('Henri-Georges Clouzot', 'Yves Montand') 1
('Henry Koster', 'James Stewart') 1
('Henry Selick', 'Dakota Fanning') 1
('Henry Selick', 'Danny Elfman') 1
('Hideaki Anno', 'Kazuya Tsurumaki') 1
('Hirokazu Koreeda', 'Lily Franky') 1
('Hiromasa Yonebayashi', 'Amy Poehler') 1
('Hong-jin Na', 'Kim Yoon-seok') 1
('Howard Hawks', 'Arthur Rosson') 1
('Howard Hawks', 'Cary Grant') 1
('Howard Hawks', 'Humphrey Bogart') 2
('Howard Hawks', 'John Wayne') 1
('Howard Hawks', 'Katharine Hepburn') 1
('Howard Hawks', 'Richard Rosson') 1
('Hrishikesh Mukherjee', 'Rajesh Khanna') 1
('Imtiaz Ali', 'Ranbir Kapoor') 1
('Imtiaz Ali', 'Shahid Kapoor') 1
('Ingmar Bergman', 'Bertil Guve') 1
('Ingmar Bergman', 'Bibi Andersson') 1
('Ingmar Bergman', 'Harriet Andersson') 1
('Ingmar Bergman', 'Ingrid Bergman') 1
('Ingmar Bergman', 'Max von Sydow') 2
('Ingmar Bergman', 'Victor Sjöström') 1
('Irvin Kershner', 'Mark Hamill') 1
('Isao Takahata', 'Chloë Grace Moretz') 1
('Isao Takahata', 'Miki Imai') 1
('Isao Takahata', 'Tsutomu Tatsumi') 1
('Ivan Reitman', 'Bill Murray') 1
('J. Lee Thompson', 'Gregory Peck') 1
('J.J. Abrams', 'Chris Pine') 2
('J.J. Abrams', 'Daisy Ridley') 1
('Jack Clayton', 'Deborah Kerr') 1
('Jaco Van Dormael', 'Jared Leto') 1
('Jacques Audiard', 'Tahar Rahim') 1
('Jacques Tourneur', 'Robert Mitchum') 1
('Jae-young Kwak', 'Tae-Hyun Cha') 1
('James Algar', 'Samuel Armstrong') 1
('James Cameron', 'Arnold Schwarzenegger') 2
('James Cameron', 'Leonardo DiCaprio') 1
('James Cameron', 'Sam Worthington') 1
('James Cameron', 'Sigourney Weaver') 1
('James Foley', 'Al Pacino') 1
('James Frawley', 'Jim Henson') 1
('James Gunn', 'Chris Pratt') 2
('James Ivory', 'Anthony Hopkins') 1
('James L. Brooks', 'Jack Nicholson') 1
('James Mangold', 'Hugh Jackman') 1
('James Mangold', 'Joaquin Phoenix') 1
('James Mangold', 'Matt Damon') 1
('James Mangold', 'Russell Crowe') 1
('James Marsh', 'Eddie Redmayne') 1
('James McTeigue', 'Hugo Weaving') 1
('James Simone', 'Hiromasa Yonebayashi') 1
('James Wan', 'Cary Elwes') 1
('James Whale', 'Boris Karloff') 1
('James Whale', 'Claude Rains') 1
('James Whale', 'Colin Clive') 1
('Je-kyu Kang', 'Jang Dong-Gun') 1
('Jean Renoir', 'Jean Gabin') 1
('Jean Renoir', 'Marcel Dalio') 1
('Jean-Jacques Annaud', 'Jude Law') 1
('Jean-Jacques Annaud', 'Sean Connery') 1
('Jean-Luc Godard', 'Anna Karina') 1
('Jean-Luc Godard', 'Jean-Paul Belmondo') 1
('Jean-Marc Vallée', 'Matthew McConaughey') 1
('Jean-Marc Vallée', 'Michel Côté') 1
('Jean-Pierre Jeunet', 'Audrey Tautou') 2
('Jean-Pierre Melville', 'Alain Delon') 1
('Jee-woon Kim', 'Lee Byung-Hun') 1
('Jeethu Joseph', 'Mohanlal') 1
('Jemaine Clement', 'Taika Waititi') 1
('Jeong-beom Lee', 'Won Bin') 1
('Jessie Nelson', 'Sean Penn') 1
('Jim Abrahams', 'David Zucker') 1
('Jim Jarmusch', 'Johnny Depp') 1
('Jim Jarmusch', 'Tom Waits') 1
('Jim Jarmusch', 'Winona Ryder') 1
('Jim Sheridan', 'Daniel Day-Lewis') 2
('Jim Sheridan', 'Paddy Considine') 1
('Joe Johnston', 'Jake Gyllenhaal') 1
('Joe Wright', 'Keira Knightley') 2
('Joel Coen', 'Ethan Coen') 6
('Joel Schumacher', 'Michael Douglas') 1
('John Boorman', 'Jon Voight') 1
('John Cameron Mitchell', 'John Cameron Mitchell') 1
('John Carney', 'Ferdia Walsh-Peelo') 1
('John Carney', 'Glen Hansard') 1
('John Carpenter', 'Donald Pleasence') 1
('John Carpenter', 'Kurt Russell') 1
('John Ford', 'Henry Fonda') 1
('John Ford', 'James Stewart') 1
('John Ford', 'John Wayne') 3
('John Frankenheimer', 'Frank Sinatra') 1
('John G. Avildsen', 'Sylvester Stallone') 1
('John Hughes', 'Emilio Estevez') 1
('John Hughes', 'Matthew Broderick') 1
('John Hughes', 'Steve Martin') 1
('John Huston', 'Humphrey Bogart') 4
('John Huston', 'Sean Connery') 1
('John Landis', 'John Belushi') 1
('John Lasseter', 'Ash Brannon') 1
('John Lasseter', 'Tom Hanks') 1
('John Lee Hancock', 'Quinton Aaron') 1
('John McTiernan', 'Arnold Schwarzenegger') 1
('John McTiernan', 'Bruce Willis') 2
('John Schlesinger', 'Dustin Hoffman') 1
('John Singleton', 'Cuba Gooding Jr.') 1
('John Sturges', 'Steve McQueen') 1
('John Sturges', 'Yul Brynner') 1
('John Woo', 'Yun-Fat Chow') 2
('Jon Avnet', 'Kathy Bates') 1
('Jon Favreau', 'Robert Downey Jr.') 1
('Jonathan Dayton', 'Valerie Faris') 1
('Jonathan Demme', 'Jodie Foster') 1
('Jonathan Demme', 'Tom Hanks') 1
('Jonathan Levine', 'Joseph Gordon-Levitt') 1
('Jonathan Lynn', 'Joe Pesci') 1
('Jordan Peele', 'Daniel Kaluuya') 1
('Joseph Kosinski', 'Josh Brolin') 1
('Joseph L. Mankiewicz', 'Bette Davis') 1
('Joseph L. Mankiewicz', 'Laurence Olivier') 1
('Joseph Sargent', 'Walter Matthau') 1
('Josh Boone', 'Shailene Woodley') 1
('Josh Cooley', 'Tom Hanks') 1
('Joss Whedon', 'Nathan Fillion') 1
('Joss Whedon', 'Robert Downey Jr.') 1
('José Padilha', 'Wagner Moura') 2
('Juan José Campanella', 'Ricardo Darín') 1
('Jules Dassin', 'Jean Servais') 1
('Julian Schnabel', 'Laura Obiols') 1
('Kabir Khan', 'Salman Khan') 1
('Kaige Chen', 'Leslie Cheung') 1
('Kar-Wai Wong', 'Brigitte Lin') 1
('Kar-Wai Wong', 'Leon Lai') 1
('Kar-Wai Wong', 'Tony Chiu-Wai Leung') 1
('Karan Johar', 'Shah Rukh Khan') 1
('Katsuhiro Ôtomo', 'Mitsuo Iwata') 1
('Ken Annakin', 'Andrew Marton') 1
('Ken Loach', 'Laura Obiols') 1
('Kenneth Branagh', 'Kenneth Branagh') 1
('Kenneth Lonergan', 'Casey Affleck') 1
('Kevin Altieri', 'Boyd Kirkland') 1
('Kevin Costner', 'Kevin Costner') 1
('Kevin Macdonald', 'James McAvoy') 1
('Kevin Reynolds', 'Jim Caviezel') 1
('Kevin Smith', "Brian O'Halloran") 1
('Ki-duk Kim', 'Ki-duk Kim') 1
('Ki-duk Kim', 'Seung-Yun Lee') 1
('Kinji Fukasaku', 'Tatsuya Fujiwara') 1
('Krzysztof Kieslowski', 'Irène Jacob') 2
('Krzysztof Kieslowski', 'Juliette Binoche') 1
('Krzysztof Kieslowski', 'Zbigniew Zamachowski') 1
('Lana Wachowski', 'Lilly Wachowski') 1
('Lars von Trier', 'Björk') 1
('Lars von Trier', 'Emily Watson') 1
('Lars von Trier', 'Nicole Kidman') 1
('Lasse Hallström', 'Johnny Depp') 1
('Lasse Hallström', 'Richard Gere') 1
('Lee Tamahori', 'Rena Owen') 1
('Lee Unkrich', 'Adrian Molina') 1
('Lee Unkrich', 'Tom Hanks') 1
('Lenny Abrahamson', 'Brie Larson') 1
('Leo McCarey', 'Groucho Marx') 1
('Levent Semerci', 'Erdem Can') 1
('Lewis Milestone', 'Lew Ayres') 1
('Louis Malle', 'Gaspard Manesse') 1
('Luc Besson', 'Bruce Willis') 1
('Luc Besson', 'Jean Reno') 1
('Luca Guadagnino', 'Armie Hammer') 1
('Luis Buñuel', 'Catherine Deneuve') 1
('Luis Buñuel', 'Fernando Rey') 1
('Luis Buñuel', 'Silvia Pinal') 1
('Lukas Moodysson', 'Oksana Akinshina') 1
('M. Night Shyamalan', 'Bruce Willis') 1
('Majid Majidi', 'Mohammad Amir Naji') 1
('Makoto Shinkai', 'Ryûnosuke Kamiki') 1
('Mamoru Hosoda', 'Aoi Miyazaki') 1
('Mamoru Hosoda', 'Riisa Naka') 1
('Mamoru Oshii', 'Atsuko Tanaka') 1
('Marc Caro', 'Jean-Pierre Jeunet') 1
('Marc Forster', 'Johnny Depp') 1
('Marc Webb', 'Chris Evans') 1
('Marc Webb', 'Zooey Deschanel') 1
('Mark Herman', 'Asa Butterfield') 1
('Mark Osborne', 'Jeff Bridges') 1
('Mark Rydell', 'Katharine Hepburn') 1
('Martin Brest', 'Al Pacino') 1
('Martin Campbell', 'Daniel Craig') 1
('Martin McDonagh', 'Colin Farrell') 1
('Martin McDonagh', 'Frances McDormand') 1
('Martin Rosen', 'John Hubley') 1
('Martin Scorsese', 'Griffin Dunne') 1
('Martin Scorsese', 'Leonardo DiCaprio') 3
('Martin Scorsese', 'Robert De Niro') 6
('Martin Zandvliet', 'Roland Møller') 1
('Mary Harron', 'Christian Bale') 1
('Masaki Kobayashi', 'Tatsuya Nakadai') 1
('Mathieu Kassovitz', 'Vincent Cassel') 1
('Matt Reeves', 'Gary Oldman') 1
('Matt Ross', 'Viggo Mortensen') 1
('Matthew Vaughn', 'Aaron Taylor-Johnson') 1
('Matthew Vaughn', 'Charlie Cox') 1
('Matthew Vaughn', 'Colin Firth') 1
('Matthew Vaughn', 'James McAvoy') 1
('Matthew Warchus', 'Bill Nighy') 1
('Meghna Gulzar', 'Alia Bhatt') 1

In [32]:
duo.get_group(('Aamir Khan', 'Amole Gupte'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
65,Taare Zameen Par,2007,165,Drama,8.4,Aamir Khan,Amole Gupte,168895,1223869.0,NaN

In [31]:
duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [36]:
duo['Gross'].sum().sort_values(ascending=False)

Director              Star1
Akira Kurosawa        Toshirô Mifune     2.999877e+09
Anthony Russo         Joe Russo          2.205039e+09
Billy Wilder          William Holden     1.286779e+09
Christopher Nolan     Christian Bale     1.242940e+09
Werner Herzog         Klaus Kinski       1.124605e+09
                                             ...
Jeong-beom Lee        Won Bin            6.460000e+03
Shane Meadows         Paddy Considine    6.013000e+03
Jaco Van Dormael      Jared Leto         3.600000e+03
Thomas Jahn           Til Schweiger      3.296000e+03
Anders Thomas Jensen  Ulrich Thomsen     1.305000e+03
Name: Gross, Length: 898, dtype: float64

In [34]:
imdb.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [38]:
imdb.groupby(['Genre','Star1'])['Metascore'].mean().sort_values(ascending=False).reset_index()

       Genre                     Star1  Metascore
0    Mystery             James Stewart      100.0
1      Drama                Cary Grant      100.0
2      Drama           Humphrey Bogart      100.0
3      Drama              Orson Welles      100.0
4      Drama            Ellar Coltrane      100.0
..       ...                       ...        ...
824  Fantasy             Werner Krauss        NaN
825  Mystery  Bernard-Pierre Donnadieu        NaN
826  Mystery             Jose Coronado        NaN
827  Mystery          Laurence Olivier        NaN
828  Mystery               Vidya Balan        NaN

[829 rows x 3 columns]

In [40]:
ipl=pd.read_csv('deliveries.csv')
ipl.head(3)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [41]:
ipl.shape

(150460, 21)

In [42]:
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150460 entries, 0 to 150459
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          150460 non-null  int64
 1   inning            150460 non-null  int64
 2   batting_team      150460 non-null  object
 3   bowling_team      150460 non-null  object
 4   over              150460 non-null  int64
 5   ball              150460 non-null  int64
 6   batsman           150460 non-null  object
 7   non_striker       150460 non-null  object
 8   bowler            150460 non-null  object
 9   is_super_over     150460 non-null  int64
 10  wide_runs         150460 non-null  int64
 11  bye_runs          150460 non-null  int64
 12  legbye_runs       150460 non-null  int64
 13  noball_runs       150460 non-null  int64
 14  penalty_runs      150460 non-null  int64
 15  batsman_runs      150460 non-null  int64
 16  extra_runs        150460 non-null  int64
 17  total_runs        150460 non-null  int64
 18  player_dismissed  7438 non-null    object
 19  dismissal_kind    7438 non-null    object
 20  fielder           5369 non-null    object
dtypes: int64(13), object(8)
memory usage: 24.1+ MB

In [44]:
ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False)

batsman
SK Raina        4548
V Kohli         4423
RG Sharma       4207
G Gambhir       4132
DA Warner       4014
                ...
RR Bhatkal         0
M Ashwin           0
Abdur Razzak       0
IC Pandey          0
Sunny Gupta        0
Name: batsman_runs, Length: 461, dtype: int64

In [47]:
ipl[ipl['batsman_runs']==6].groupby('batsman')['bowler'].count().sort_values(ascending=False)

batsman
CH Gayle         266
SK Raina         174
RG Sharma        173
DA Warner        160
V Kohli          160
                ...
Sohail Tanvir      1
T Kohli            1
T Henderson        1
A Mithun           1
A Choudhary        1
Name: bowler, Length: 301, dtype: int64

In [57]:
ipl[(ipl['over'] > 15) & (ipl['batsman_runs'].isin([4, 6]))].groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
MS Dhoni          269
RG Sharma         188
KA Pollard        182
AB de Villiers    179
V Kohli           139
                 ...
Shivam Sharma       1
AR Bawne            1
Sunny Singh         1
Shoaib Malik        1
TS Mills            1
Name: batsman, Length: 321, dtype: int64

In [60]:
ipl[ipl['batsman']=='V Kohli'].groupby(['bowling_team'])['batsman_runs'].sum().reset_index()

               bowling_team  batsman_runs
0       Chennai Super Kings           706
1           Deccan Chargers           306
2          Delhi Daredevils           661
3             Gujarat Lions           283
4           Kings XI Punjab           483
5      Kochi Tuskers Kerala            50
6     Kolkata Knight Riders           391
7            Mumbai Indians           447
8             Pune Warriors           128
9          Rajasthan Royals           258
10   Rising Pune Supergiant            83
11  Rising Pune Supergiants           188
12      Sunrisers Hyderabad           439